lib/audiotech_web/router.ex
defmodule AudiotechWeb.Router do
  use AudiotechWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AudiotechWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/user/:username", PageController, :user
    get "/articles/", ArticleController, :index
    get "/articles/:id", ArticleController, :show
    post "/article/create", ArticleController, :create
    post "/articles/:id/edit", ArticleController, :edit
    post "/articles/:id/delete", ArticleController, :delete
    post "/login", PageController, :login
    post "/logout", PageController, :logout
    post "/update", PageController, :update
    post "/signup", PageController, :signup
    post "/terminate", PageController, :terminate
  end

  # Other scopes may use custom stacks.
  # scope "/api", AudiotechWeb do
  #   pipe_through :api
  # end
end

lib/audiotech/article.ex
defmodule Audiotech.Article do
  use Ecto.Schema
  import Ecto.Changeset

  schema "articles" do
    field :content, :string
    field :title, :string
    belongs_to :user, Audiotech.Users

    timestamps()
  end

  def contents(article) do
    opts = %Earmark.Options{sanitize: true}
    {:safe, Earmark.as_html!(article.content, opts)}
  end

  @doc false
  def changeset(article, attrs) do
    article
    |> cast(attrs, [:user_id, :title, :content])
    |> validate_required([:user_id, :title, :content])
  end
end

lib/audiotech_web/controllers/article_controller.ex
defmodule AudiotechWeb.ArticleController do
  use AudiotechWeb, :controller
  import Ecto.Query, only: [from: 2]

  def index(conn, _params) do
    cusername = get_session(conn, :username) || ""
    {cuser, cmod} = Audiotech.Users.load_user(cusername)
    articles = from(a in Audiotech.Article, preload: [:user], order_by: [desc: [a.updated_at]])

    users =
      from(u in Audiotech.Users,
        join: a in Audiotech.Article,
        on: u.id == a.user_id,
        preload: [articles: ^articles],
        order_by: [desc: max(a.inserted_at)],
        group_by: u.id
      )
      |> Audiotech.Repo.all()

    env = %{
      title: "articles",
      token: get_csrf_token(),
      cuser: cuser,
      cmod: cmod,
      users: users
    }

    render(conn, "index.html", env)
  end

  def show(conn, params) do
    id = params["id"]
    cusername = get_session(conn, :username) || ""
    {cuser, cmod} = Audiotech.Users.load_user(cusername)

    case Audiotech.Repo.all(from(a in Audiotech.Article, where: a.id == ^id, preload: [:user])) do
      [article] ->
        env = %{
          title: article.title,
          cuser: cuser,
          cmod: cmod,
          article: article,
          token: get_csrf_token()
        }

        conn
        |> render("show.html", env)

      _ ->
        conn
        |> put_status(404)
        |> put_view(AudiotechWeb.ErrorView)
        |> render("404.html")
    end
  end

  def edit(conn, params) do
    id = params["id"]
    username = get_session(conn, :username)

    {:ok, article} =
      Audiotech.Repo.transaction(fn ->
        user =
          from(u in Audiotech.Users, where: u.username == ^username)
          |> Audiotech.Repo.one!()

        article =
          from(a in Audiotech.Article,
            left_join: m in Audiotech.Moderator,
            where: a.id == ^id and (a.user_id == ^user.id or (m.user_id == ^user.id and not is_nil(m.id)))
          )
          |> Audiotech.Repo.one!()

        Audiotech.Repo.update(
          article
          |> Audiotech.Article.changeset(%{title: params["title"], content: params["content"]})
        )

        article
      end)

    conn |> redirect(to: "/articles/#{article.id}")
  end

  def delete(conn, params) do
    id = params["id"]
    username = get_session(conn, :username)

    {:ok, _} =
      Audiotech.Repo.transaction(fn ->
        user = Audiotech.Repo.one!(from(u in Audiotech.Users, where: u.username == ^username))

        article =
          Audiotech.Repo.one!(
            from(a in Audiotech.Article,
              join: m in Audiotech.Moderator,
              where: a.id == ^id and (a.user_id == ^user.id or m.user_id == ^user.id)
            )
          )

        Audiotech.Repo.delete!(article)
      end)

    conn |> redirect(to: "/user/#{username}")
  end

  def create(conn, params) do
    username = get_session(conn, :username)

    {:ok, article} =
      Audiotech.Repo.transaction(fn ->
        user =
          from(u in Audiotech.Users, where: u.username == ^username)
          |> Audiotech.Repo.one!()

        article = %Audiotech.Article{
          user_id: user.id,
          title: params["title"],
          content: params["content"]
        }

        Audiotech.Repo.insert!(article)
      end)

    conn |> redirect(to: "/articles/#{article.id}")
  end
end

lib/audiotech_web/views/article_view.ex
defmodule AudiotechWeb.ArticleView do
  use AudiotechWeb, :view
end

lib/audiotech_web/templates/article/index.html.eex
<%= for user <- @users do %>
  <h1><a href="/user/<%= user.username %>"><%= user.username %></a></h1>
  <%= for article <- user.articles do %>
    <div class="article">
      <h1><a href="/articles/<%= article.id %>"><%= article.title %></a></h1>
      <h2><a href="/user/<%= article.user.username %>"><%= article.user.username %></a></h2>
      <h2><span class="date"><%= Audiotech.DateTime.from_naive(article.inserted_at) %></span>&mdash;<span class="date"><%= Audiotech.DateTime.from_naive(article.updated_at) %></span></h2>
      <div>
        <%= article |> Audiotech.Article.contents %>
      </div>
    </div>
  <% end %>
<% end %>
<%= if @cuser do %>
  <form method="POST" action="/article/create">
    <input name="_csrf_token" type="hidden" value="<%= @token %>">
    <input name="title"><br>
    <textarea rows="24" cols="80" name="content"></textarea><br>
    <input type="submit">
  </form>
<% end %>

lib/audiotech_web/templates/article/show.html.eex
<div class="article">
  <h1><a href="/articles/<%= @article.id %>"><%= @article.title %></a></h1>
  <h2><a href="/user/<%= @article.user.username %>"><%= @article.user.username %></a></h2>
      <h2><span class="date"><%= Audiotech.DateTime.from_naive(@article.inserted_at) %></span>&mdash;<span class="date"><%= Audiotech.DateTime.from_naive(@article.updated_at) %></span></h2>
  <div>
    <%= @article |> Audiotech.Article.contents %>
  </div>
</div>
<%= if @cuser && (@cuser.id === @article.user_id || @cmod) do %>
  <form method="POST" action="<%= Routes.article_path @conn, :edit, @article.id %>">
      <input name="_csrf_token" type="hidden" value="<%= @token %>">
      <input name="title" value="<%= @article.title %>"><br>
      <textarea rows="24" cols="80" name="content"><%= @article.content %></textarea><br>
      <input type="submit">
  </form>
  <form id="delete-article" method="POST" action="/articles/<%= @article.id %>/delete">
      <input name="_csrf_token" type="hidden" value="<%= @token %>">
      <input type="submit" value="Delete">
  </form>
<% end %>